# Site
name: "Kletterkompass"
title: "Kletterkompass"
description: "Du suchst nach der perfekten Halle? Wir haben sie für dich getestet!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: 'https://www.kletterkompass.com'
google_analytics: 'G-GXVL1JJ98M'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: chrkngchr@gmail.com

# Authors
authors:
  robin:
    name: Niklas
    display_name: Niklas    
    avatar: 'assets/images/old.jpg'
    email: info@kletterkompass.com
    description: "Vor 7 Jahren habe ich mit dem Bouldern im Boulderplanet Köln angefangen und es war Liebe auf den ersten Blick. Ich bin immer in der Region geblieben und hab über die Jahre viele Hallen um Köln herum getestet."
  sophie:
    name: Franzi
    display_name: Franzi
    avatar: 'assets/images/avatar_franzi.jpg'
    email: info@kletterkompass.com
    description: "Vor 5 Jahren hat mich Niklas zum Bouldern mitgenommen und seit meinem Urban-Sportsclub-Abo gehe ich wieder regelmäßig. Durch meinen Bürojob sitze ich den ganzen Tag rum und Bouldern ist die perfekte Unterstützung für meinen Rücken. Ich komme aus Köln, arbeite gerade aber in Duisburg."
  chris:
    name: Chris
    display_name: Chris    
    avatar: 'assets/images/avatar.jpg'
    email: info@kletterkompass.com
    description: "Im ersten Semester haben Niklas und ich uns kennengelernt und gemeinsam das Bouldern für uns entdeckt. Durch meinen Studienverlauf haben sich unsere Wege getrennt, aber das Bouldern blieb. Ich hab in verschiedenen Städten studiert und natürlich jede Halle vor Ort getestet."
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
